---
- name: Copy hook to enable acmetool to reload services
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', acmetool__reload_hook) }}"
    dest: '/etc/acme/hooks/'
    owner: root
    group: root
    mode: 'u=rx,g=rx,o=rx'

- name: Create hook configuration to reload services via ansible
  become: true
  ansible.builtin.template:
    src: 'templates/acmetool_reload.j2'
    dest: '/etc/default/acme-reload'
    owner: root
    group: root
    mode: 'u=rx,g=rx,o=rx'

- name: Copy hook to enable acmetool to restart services
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', acmetool__restart_hook) }}"
    dest: '/etc/acme/hooks/'
    owner: root
    group: root
    mode: 'u=rx,g=rx,o=rx'

- name: Create hook configuration to restart services via ansible
  become: true
  ansible.builtin.template:
    src: 'templates/acmetool_restart.j2'
    dest: '/etc/default/acme-restart'
    owner: root
    group: root
    mode: 'u=rx,g=rx,o=rx'
