---
name: 'Yamllint GitHub Actions'

# yamllint disable-line rule:truthy
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '23 6 * 3,6,9,12 *'

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_config_filepath: './.yamllint'
